name: $pluginName
main: $pluginMain
api-version: "1.19"
version: $version
libraries:
  - io.github.monun:kommand-core:$kommandVersion
  - io.github.monun:tap-core:$tapVersion
#  - io.github.monun:invfx:$invfxVersion
#  - org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion
#  - io.github.monun:heartbeat-coroutines:$hbCoroutinesVersion
#  - world.komq:parallel-universe-core:$parallelUniverseVersion
